[
build
]
  functions = "netlify/functions"
  publish = "/"

[
functions
]
  external_node_modules = ["@octokit/rest"]
  node_bundler = "esbuild"

[[
redirects
]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

  